server:
  port: 8080

#静态资源配置
resources:
  static-locations: classpath:static/


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_database?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tbyf.demo.springbootdemo.model.Account

logging:
  level:
    com:
      example:
        mapper : debug


